version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: exercise
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.22.1-alpine
    container_name: exercise-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
